services:
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    user: 1000:1000
    environment:
      - TZ=Europe/Amsterdam
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_USER=${GF_SMTP_USER}
    volumes:
      - ./data/:/var/lib/grafana/
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.huis.wtf`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - traefik
      - grafana

networks:
  traefik:
    external: true
  grafana:
    external: true
