services:
  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki
    user: "1000:1000"
    ports:
      - 3100:3100
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./data/:/loki/
    restart: unless-stopped
